name: Node.js Setup Workflow

on:
  workflow_call:
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: 'node'
